### ISSUE TITLE
Typo in the command of msconvert

### ISSUE THREAD

**Issue by ptdtan** [cptac3-cdap/galaxy-tools#1]
We are getting error when running msconvert, which we believe it is because there is a typo in the script.
  `${__tool_directory__}/docker_run_with_timeout.sh 55m docker run -v `pwd`:/data/ -v /mnt/galaxy/files:/files/ chambm/pwiz-skyline-i-agree-to-the-vendor-licenses:${advanced.tag} wine msconvert ${centroid} ${zlib} --${outfmt.split('.',1)[0]} /data/${input.name} &&`

Which should be `  ${__tool_directory__}/docker_run_with_timeout.sh 55m -v `pwd`:/data/ -v /mnt/galaxy/files:/files/ chambm/pwiz-skyline-i-agree-to-the-vendor-licenses:${advanced.tag} wine msconvert ${centroid} ${zlib} --${outfmt.split('.',1)[0]} /data/${input.name} &&`

**Comment by edwardsnj** [comment]
Thank you for spotting that. I'll push a new tools release this morning.
